spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  
  

